-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 03:31:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGB` DEFAULT CHARACTER SET utf8 ;
USE `SGB` ;

-- -----------------------------------------------------
-- Table `SGB`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `status` VARCHAR(20) NULL,
  `funcao` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`enderecos` (
  `id_enderecos` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_enderecos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `tipo_produto` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `preco` DOUBLE NULL,
  `quantidade_estoque` VARCHAR(45) NULL,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`pedidos` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `hora` TIME NULL,
  `valor_total` FLOAT NULL,
  PRIMARY KEY (`id_pedidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`itens_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`itens_pedido` (
  `id_itens_pedido` INT NOT NULL AUTO_INCREMENT,
  `descicao` VARCHAR(60) NOT NULL,
  `valor` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_itens_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`fornecedores` (
  `id_fornecedores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fornecedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `total_prod` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`caixa` (
  `id_caixa` INT NOT NULL AUTO_INCREMENT,
  `saldo_inicial` FLOAT NULL,
  `saldo_final` FLOAT NULL,
  `hora_inicial` TIME NULL,
  `hora_final` TIME NULL,
  `data` DATE NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_caixa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGB`.`formas_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGB`.`formas_pagamentos` (
  `id_formas_pagamentos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_formas_pagamentos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
